# Generated by Django 2.2.6 on 2019-10-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
