# Generated by Django 2.2.6 on 2020-04-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Image'),
        ),
        migrations.AddField(
            model_name='socio',
            name='profile_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.IntegerField(choices=[(0, 'UserProfile'), (1, 'BlogPost'), (2, 'ShopItem'), (3, 'SectionHeader')]),
        ),
    ]
