# Generated by Django 2.2.6 on 2020-04-28 14:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200426_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/toni/Desktop/Trabajo/Proyectos/Propios/ONG Dani/trees_ong_back/media/images'), upload_to=''),
        ),
    ]
