# Generated by Django 2.2.6 on 2020-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200428_1438'),
        ('blog', '0002_auto_20200415_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(null=True, to='api.Image'),
        ),
    ]
