# Generated by Django 2.2.6 on 2020-04-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
        ('shop', '0002_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='api.Image'),
        ),
    ]
